name: Account
on:
  workflow_dispatch:
    inputs:
      SERIAL:
        description: 'Tên serial'
        required: true
        default: ''
      WIDGETID:
        description: 'Nhập id widget'
        required: true
        default: ''
permissions: write-all
jobs:
  build:
    name: 'See progress'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Start process'
        env:
          SERIAL: ${{ inputs.SERIAL }}
          WIDGETID: ${{ inputs.WIDGETID }}
        run: |
          # Kakathic
          curl -s -G -L https://github.com/Zenlua/Widget/releases/download/tmp/vip.txt > vip.txt
          echo "$WIDGETID" | awk '{print "'$SERIAL'="$0}' >> vip.txt
      - name: Upload txt
        uses: softprops/action-gh-release@v2
        with:
          name: Tmp
          tag_name: tmp
          files: vip.txt
